name: Report a bug
description: 🐛 Report a reproducible bug and help us improve
type: bug
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > This form is only for reporting _reproducible bugs_.
        > If you're looking for assistance with using YOURLS, please visit our [discussions community](https://github.com/orgs/YOURLS/discussions) instead.
        
        > [!TIP]
        > Check [exiting issues](https://github.com/YOURLS/YOURLS/issues), opened or closed.
        > Similar cases might have been answered already.
  - type: checkboxes
    attributes:
      label: Self troubleshooting
      description: Before submitting you have checked your deployment validity and followed usual troubleshooting steps
      options:
        - label: I've read the [documentation](https://yourls.org/) and made sure to follow it.
          required: true
        - label: I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.
          required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Relevant [release of YOURLS](https://github.com/YOURLS/YOURLS/releases)
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: What happened?
      placeholder: |
        A clear and concise description of what the bug is.
        A screenshot to illustrate the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What was expected?
      placeholder: |
        A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem.
      placeholder: |
        1. Go to …
        2. Click on …
        3. Scroll down to …
        4. See error
  - type: textarea
    attributes:
      label: Context
      placeholder: |
        Any additional information, configuration or data that might be necessary to reproduce the issue.
        Other software version.
    validations:
      required: false
