name: Bug report
description: 🐛 Report a reproducible bug and help us improve
labels:
  - bug
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).
          required: true
  - type: checkboxes
    id: relevance
    attributes:
      label: Submission validity
      description: This new report is relevant and not duplicated
      options:
        - label: This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
          required: true
        - label: I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.
          required: true
  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Personnal troubleshooting
      description: Before submitting you have checked your deployment and followed usual troubleshooting steps
      options:
        - label: I've read the [documentation](https://yourls.org/) and made sure to follow them.
          required: true
        - label: I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.
          required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: YOURLS version used
      placeholder: X.Y.Z
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: What happened?
      placeholder: |
        A clear and concise description of what the bug is.
        A screenshot to illustrate the issue.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expectation
      description: What was expected?
      placeholder: |
        A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem.
      placeholder: |
        1. Go to …
        2. Click on …
        3. Scroll down to …
        4. See error
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What was expected?
      placeholder: |
        Any additional information, configuration or data that might be necessary to reproduce the issue.
        Other software version.
    validations:
      required: false
