blank_issues_enabled: true
contact_links:
  - name: Community Forum
    url: https://discourse.yourls.org
    about: Have a question? Not sure if your issue affects everyone reproducibly? The quickest way to get help is on the YOURLS Discourse.
