name: Suggest a feature
description: 💡 Suggest an idea for this project
Type: enhancement
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > This form is only for submitting _well-formed proposals_ to extend or modify YOURLS.
        > If you're looking for assistance with using YOURLS, please visit our [discussions community](https://github.com/orgs/YOURLS/discussions) instead.
        
        > [!TIP]
        > Check [exiting issues](https://github.com/YOURLS/YOURLS/issues), opened or closed.
        > Similar requests might have been opened or answered already.
  - type: textarea
    attributes:
      label: Proposed functionality
      description:
      placeholder: |
        One paragraph explanation of the feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description:
      placeholder: |
        Why are we doing this?
        What use cases does it support?
        What is the expected outcome?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Potential solution
      description:
      placeholder: |
        A clear and concise description of what you want to happen.
        Is your feature request related to a problem?
        Describe alternatives you've considered.
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
